### generate `.gct` file from DESeq2 normed data for computing EMT score

In [17]:
import os
import pandas as pd

os.chdir('/Users/jplab/Desktop/DAILY_CODE_DATA/2022-4/data/4-6_EMTScore/gct/')

In [18]:
# deseq2 normed data with gene name
deseq2_norm_counts = '/Users/jplab/Desktop/DAILY_CODE_DATA/2022-4/code/4-6_EMTScore/counts/mRNA_seq_FOXA1_KD_NC_2022221.tsv'
df_deseq2_norm_counts = pd.read_csv(deseq2_norm_counts, sep='\t',header=0)
df_deseq2_norm_counts.drop_duplicates(subset=['geneid'], inplace=True)


df_deseq2_norm_counts

,geneid,shFOXA1_B14_1,shFOXA1_B14_2,shFOXA1_DMSO_1,shFOXA1_DMSO_2,shFOXA1_TGFb_1,shFOXA1_TGFb_2,shNC_B14_1,shNC_B14_2,shNC_DMSO_1,shNC_DMSO_2,shNC_TGFb_1,shNC_TGFb_2,baseMean,external_gene_name
0,ENSG00000000003,373.974649,343.474763,316.510621,345.137014,526.566060,465.495166,387.791948,396.581178,399.505536,361.375199,468.947896,533.221062,NaN,TSPAN6
1,ENSG00000000005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.186580,NaN,TNMD
2,ENSG00000000419,406.761468,428.228277,386.039183,447.014807,445.387125,347.240043,373.707495,366.374749,412.234879,315.317576,384.187176,395.135927,NaN,DPM1
3,ENSG00000000457,127.048922,139.174190,153.585481,148.658413,140.417616,105.354564,141.783497,169.545762,129.251791,170.944641,135.432890,161.453389,NaN,SCYL3
4,ENSG00000000460,184.425854,164.154173,171.227057,163.212383,165.648906,182.757917,247.886378,295.243481,272.212105,257.745547,243.226414,306.973879,NaN,C1orf112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58730,ENSG00000285990,1.024588,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.885724,0.000000,0.000000,NaN,NBEAP6
58731,ENSG00000285991,0.000000,4.460711,2.075479,0.000000,1.097013,7.525326,3.755854,9.744009,2.937541,0.885724,6.449185,4.248773,NaN,RAET1E
58732,ENSG00000285992,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
58733,ENSG00000285993,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
58734,ENSG00000285994,1.024588,0.892142,4.150959,2.079139,0.000000,0.000000,0.000000,0.000000,0.000000,0.885724,0.000000,0.000000,NaN,NaN

### generate gct file here
* example

```
#1.2					
11829	4				
NAME	Description	shNC_B14_1	shNC_B14_2	shFOXA1_B14_1	shFOXA1_B14_2
TSPAN6	na	407.1578142	414.9665223	384.6240874	356.4576284
DPM1	na	392.3700001	383.3597356	418.3445553	444.4147055
SCYL3	na	148.863995	177.4058351	130.6668132	144.4347793
C1orf112	na	260.2655277	308.9308508	189.6776321	170.3589704
```

In [19]:
columns = df_deseq2_norm_counts.columns.to_list()
start_offset = columns.index('geneid')
end_offset = columns.index('baseMean')
sample_names = columns[start_offset+1:end_offset]
sample_numbers = len(sample_names)

# df_deseq2_norm_counts['baseMean'] = df_deseq2_norm_counts.mean(axis=1,numeric_only=True)

third_line = 'Name\tDescription\t' + '\t'.join(sample_names)

df_deseq2_norm_counts['Description'] = 'na'

keep_order = ['external_gene_name','Description']+sample_names
df_keep = df_deseq2_norm_counts[keep_order]
df_keep['external_gene_name'] = df_keep['external_gene_name'].str.upper()
df_keep['Description'] = df_keep['external_gene_name'].str.upper()
df_keep.rename(columns={'external_gene_name':'NAME'}, inplace=True)

df_keep.drop_duplicates(subset='NAME', keep='first', inplace=True)
df_keep.dropna(subset=['NAME'], inplace=True)

df_keep = df_keep[df_keep.mean(axis=1,numeric_only=True) > 50]

# how many genes are in the dataframe
gene_numbers = df_keep.shape[0]
gene_numbers

first_line = '#1.2'
# defalut 4, and will change by the number of actual columns
sample_numbers = 12

second_line = str(gene_numbers) + '\t' + str(sample_numbers)
second_line

/var/folders/ns/3xz044fx65q93txsfd6rthj00000gn/T/ipykernel_7387/1233673831.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_keep['external_gene_name'] = df_keep['external_gene_name'].str.upper()
/var/folders/ns/3xz044fx65q93txsfd6rthj00000gn/T/ipykernel_7387/1233673831.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_keep['Description'] = df_keep['external_gene_name'].str.upper()
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
/var/folders/ns/3xz044fx65q93txsfd6rthj00000gn/T/ipykernel_7387/1233673831.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_keep.drop_duplicates(subset='NAME', keep='first', inplace=True)
/var/folders/ns/3xz044fx65q93txsfd6rthj00000gn/T/ipykernel_7387/1233673831.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_keep.dropna(subset=['NAME'], inplace=True)

'11038\t12'

In [20]:
save_as = 'mRNA_seq_FOXA1_KD_NC_2022221.gct'

with open(save_as, 'w') as f:
    f.write(first_line + '\n')
    f.write(second_line + '\n')
    f.write(third_line + '\n')
    for index, row in df_keep.iterrows():
        f.write(row['NAME'] + '\t' + row['Description'] + '\t')
        for i,s in enumerate(sample_names):
            f.write(str(row[s]))
            if i != sample_numbers-1:
                f.write('\t')
        f.write('\n')